# comfyui node input/output types

DANBOT_MODEL_TYPE = "DANBOT_MODEL"
DANBOT_GENERATION_CONFIG_TYPE = "DANBOT_GENERATION_CONFIG"
DANBOT_CATEGORY = "prompt/Danbooru Tags Translator"

FORMAT_KWARGS_DTYPE = "DANBOT_FORMAT_KWARGS"
TEMPLATE_CONFIG_DTYPE = "DANBOT_TEMPLATE_CONFIG"
