# newlines are removed when loading

v2408-dev:
  translation: |-
    <|bos|>
    {rating}{aspect_ratio}{length}
    <|reserved_2|><|reserved_3|><|reserved_4|>
    <|translate:exact|><|input_end|>
    <copyright>

  extension: |-
    <|bos|>
    {rating}{aspect_ratio}{length}
    <|reserved_2|><|reserved_3|><|reserved_4|>
    <|translate:approx|><|input_end|>
    <copyright>{copyright}</copyright>
    <character>{character}</character>
    <general>
    <|reserved_5|>{translation}<|reserved_6|>
    <|reserved_7|>

v2408:
  translation: |-
    <|bos|>
    {rating}{aspect_ratio}{length}
    <text><|text|></text>
    <|translate:exact|><|input_end|>
    <copyright>

  extension: |-
    <|bos|>
    {rating}{aspect_ratio}{length}
    <text><|text|></text>
    <|translate:approx|><|input_end|>
    <copyright>{copyright}</copyright>
    <character>{character}</character>
    <general>
    <translation>{translation}</translation>
    <extension>
